//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Products = new HashSet<Products>();
        }
    
        public short CategoryID { get; set; }


        // Kelime anlamý = Required -> Gerekli , Validation olarak "Boç geçilemez" alanlar için kullanýlýr.
        // ErrorMessage ="Kategori Adý Boþ Geçilemez."  ifadesi boþ geçildiði takdirde gösterilecek mesaj.
        //StringLength validation ise 1.parametre olarak verilen uzunluktan fazla karater girilince ErrorMessage bastýrýr.

        [Required(ErrorMessage = "Kategori Adý Boþ Geçilemez.")]
        [StringLength(25,ErrorMessage ="En fazla 25 en az 3 karakter girilebilir.",MinimumLength =3)]
        public string CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
