//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Saleses = new HashSet<Saleses>();
        }

        public int CustormerID { get; set; }

        // Kelime anlamý = Required -> Gerekli , Validation olarak "Boç geçilemez" alanlar için kullanýlýr.
        // Required için ErrorMessage ="Kategori Adý Boþ Geçilemez."  ifadesi boþ geçildiði takdirde gösterilecek mesaj.


        //StringLength validation ise 1.parametre olarak verilen uzunluktan fazla karater girilince ErrorMessage bastýrýr.
        //StringLength validation sadece Sring tipinde propertyler için kullanýlabilir.
        //StringLength validation kullanýrken MinimumLength ile min uzunluk ayarlayabiliyoruz.

        /*
        [Range] validation ->
        Minimum Deðer (1. Parametre): Giriþin kabul edilebilir en küçük deðerini belirtir.
        Maksimum Deðer (2. Parametre): Giriþin kabul edilebilir en büyük deðerini belirtir.
        Hata Mesajý (3. Parametre): Giriþ, belirtilen aralýk dýþýndaysa gösterilecek hata mesajýný belirler.*/

        [Required(ErrorMessage = "Ad alaný boþ geçilemez.")]
        [StringLength(25, ErrorMessage = "Ad en fazla 25 en az 3 karakter olabilir.", MinimumLength = 3)]
        public string CustomerFirstName { get; set; }

        [Required(ErrorMessage = "Soyad alaný boþ geçilemez.")]
        [StringLength(25, ErrorMessage = "Soyad en fazla 25 en az 3 karakter olabilir.", MinimumLength = 3)]
        public string CustomerSurName { get; set; }

        [Required(ErrorMessage = "Yaþ alaný boþ geçilemez.")]
        [Range(18, 120, ErrorMessage = "Yaþ alaný 18-120 yaþ arasýnda olmalýdýr.")]
        public Nullable<byte> CustomerAge { get; set; }

        [Required(ErrorMessage = "Þehir alaný boþ geçilemez.")]
        [StringLength(25, ErrorMessage = "Þehir en fazla 25 en az 3 karakter olabilir.", MinimumLength = 3)]
        public string CustomerCity { get; set; }

        [Required(ErrorMessage = "Ülke alaný boþ geçilemez.")]
        [StringLength(25, ErrorMessage = "Ülke en fazla 25 en az 3 karakter olabilir.", MinimumLength = 3)]
        public string CustomerCountry { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saleses> Saleses { get; set; }
    }
}
