//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Saleses
    {
        public int SalesID { get; set; }

        
        public Nullable<int> SalesProductID { get; set; }

        [Required]
        public Nullable<int> SalesCustomerID { get; set; }

        [Required]
        [Range(1,250)]
        public Nullable<short> SalesPiece { get; set; }

        [Required]
        [Range(1, 1000000)]
        public Nullable<decimal> SalesCost { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
